"""add_kpi_targets

Revision ID: 14be7903fc36
Revises: 2b46c7cb743e
Create Date: 2026-04-03 12:07:16.748143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14be7903fc36'
down_revision: Union[str, None] = '2b46c7cb743e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpi_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('kpi_name', sa.String(length=100), nullable=False),
    sa.Column('kpi_category', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'kpi_name', 'period_year', 'period_month', name='uq_kpi_target')
    )
    op.create_index(op.f('ix_kpi_targets_site_id'), 'kpi_targets', ['site_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kpi_targets_site_id'), table_name='kpi_targets')
    op.drop_table('kpi_targets')
    # ### end Alembic commands ###
